import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import AuthProvider from "./AuthProvider"
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
