FROM node:latest

WORKDIR /src

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm run install
RUN npm run db:generate
RUN npm run build

CMD ["npm","run","start-user-app"]